apiVersion: 1
datasources:
  - name: Taskboard Prometheus
    uid: taskboard-prometheus
    type: prometheus
    access: proxy
    url: https://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 10s
      tlsSkipVerify: false
